### PR TITLE
Add Rails 5.2 and 6.0 on Ruby 2.6 to CI

### PR DESCRIPTION
**Pull request by santry**

### CODE REVIEW

**Review by pboling — APPROVED** [review]
LGTM

**Comment by pboling** [comment]
@santry, I will test out this PR against my Rails 5.2 setup, as I've got pretty good test coverage on the logging.

**Comment by santry** [comment]
@pboling that sounds great, thanks! let me know how it turns out. once we confirm it works I'll put out a new release of the gem.

**Comment by pboling** [comment]
@santry It works great :). Thanks!

**Pull request merged**
